# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.png'
      - 'img/*'
      - 'LICENSE'
      - '.gitignore'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.png'
      - 'img/*'
      - 'LICENSE'
      - '.gitignore'
      - 'docs/**'

jobs:
  build-n-test:

    runs-on: ubuntu-latest
    # See: https://github.com/marketplace/actions/skip-based-on-commit-message
    if: "!contains(github.event.head_commit.message, 'docs only')"
    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov
        python setup.py install
    - name: Test with pytest
      run: |
        pytest --cov-report term-missing --cov-config=.coveragerc --cov=redata tests
